#pragma once

#define AVE_GDI_BACKGROUND_PAINT_DO_NOT_OVERRIDE	0
#define AVE_GDI_BACKGROUND_PAINT_DO_NOT_CLEAR		1
#define AVE_GDI_BACKGROUND_PAINT_DO_CLEAR			2
#define AVE_GDI_WANTS_TO_RENDER_OVER_DEFAULT_BG		3

#define AVE_D3D_RENDERICONBUFFER_FULL				0
#define AVE_D3D_RENDERICONBUFFER_ONLY_DRAW			1
#define AVE_D3D_RENDERICONBUFFER_ONLY_SET_TEXTURE	2

#define WM_AVE_EFFECTCONFIG_OK						WM_APP + 2000


#define AVE_SUPPORTS_CONFIG							(1 << 0)
#define AVE_SUPPORTS_D3D_DRAW_OVER_REAL_WALLPAPER	(1 << 1)

#define AVE_NOTIFICATION_BEFORE_WALLPAPER_CHANGED	1
#define AVE_NOTIFICATION_AFTER_WALLPAPER_CHANGED	2